/// <reference types="node" />
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ValidatorCompiler = (() => {

    const CURRENT_DIR = fileURLToPath(new URL('.', import.meta.url));
    const SRC_DIR = resolve(CURRENT_DIR, '..', 'src');
    const CONFIG = {
        generatedValidatorFilePath: resolve(SRC_DIR, 'validator.ts')
    };

    function buildImports(): string {
        return `import {  } from "";`;
    }

    function buildInterfacesCode(): string {
        let sc = '';

        sc += `export interface Validator<S extends DSchemaWith$id> {\n`
        sc += `    isValid(data: unknown): boolean;\n`;
        sc += `    validate(data: unknown): { valid: boolean; errors?: Error[] };\n`;
        sc += `    deserialize<R extends DTypeOf<S>>(json: string): R;\n`;
        sc += `    serialize<R extends DTypeOf<S>>(data: R): string;\n`;
        sc += `}\n`;

        sc += `export interface Validators<S extends DSchemaWith$id> extends Record<string, Validator<S>> {}\n`;

        return sc;
    }

    function buildValidatorCodeBody(): string {
        let sc = '';
        sc += `${buildInterfacesCode()}\n`;

        return sc;
    }

    function buildValidatorSourceCode(): string {
        const sourceCodeHeader = `// AUTO-GENERATED FILE. DO NOT EDIT.\n// Generated by scripts/compiler.ts\n`;
        const validatorSourceCode = buildValidatorCodeBody();
        return `${sourceCodeHeader}\n${buildImports()}\n${validatorSourceCode}`;
    }

    function generateValidator(outPath: string) {
        const sourceCode = buildValidatorSourceCode();
        writeFileSync(outPath, sourceCode);
    }

    return {
        compile: () => generateValidator(CONFIG.generatedValidatorFilePath)
    };
})();

ValidatorCompiler.compile();
