import {
    AudioContentSchema,
    ChannelMetadataSchema,
    ClientConversationMemberSchema,
    ClientConversationSchema,
    ClientUserSchema,
    ClientUserSettingsNotificationsSchema,
    ContactContentSchema,
    ConversationMemberChatPrefsSchema,
    ConversationMemberSchema,
    ConversationSchema,
    DeleteContentSchema,
    DeviceChatPrefsSchema,
    DeviceNotificationPrefsSchema,
    DeviceSchema,
    DocumentContentSchema,
    EventContentSchema,
    GroupMetadataSchema,
    ImageContentSchema,
    LabelsAndCirclesSchema,
    LocationContentSchema,
    MessageExclusionSchema,
    MessageReactionSchema,
    MessageSchema,
    PollContentSchema,
    ProfileDevicesSchema,
    ProfileInfoSchema,
    ProfileRelationshipsSchema,
    ProfileSchema,
    ProfileSettingsSchema,
    SystemContentSchema,
    SystemMetadataSchema,
    TextContentSchema,
    UserRelationshipSchema,
    UserSchema,
    UserSettingsAccountSchema,
    UserSettingsBackupSchema,
    UserSettingsNotificationsSchema,
    UserSettingsPrivacySchema,
    UserSettingsSchema,
    VideoContentSchema
} from './entities';

export const SCHEMA_REGISTRY = {
    LabelsAndCirclesSchema,
    DeviceChatPrefsSchema,
    UserSettingsPrivacySchema,
    UserSettingsBackupSchema,
    UserSettingsAccountSchema,

    GroupMetadataSchema,
    ChannelMetadataSchema,
    SystemMetadataSchema,
    ConversationMemberChatPrefsSchema,

    UserSchema,
    UserSettingsNotificationsSchema,
    UserSettingsSchema,
    DeviceNotificationPrefsSchema,
    DeviceSchema,
    UserRelationshipSchema,

    ConversationSchema,
    ConversationMemberSchema,

    TextContentSchema,
    ImageContentSchema,
    VideoContentSchema,
    AudioContentSchema,
    DocumentContentSchema,
    ContactContentSchema,
    LocationContentSchema,
    PollContentSchema,
    EventContentSchema,
    SystemContentSchema,
    DeleteContentSchema,
    MessageSchema,
    MessageExclusionSchema,
    MessageReactionSchema,

    ProfileInfoSchema,
    ClientUserSettingsNotificationsSchema,
    ProfileSettingsSchema,
    ProfileDevicesSchema,
    ProfileRelationshipsSchema,
    ProfileSchema,
    ClientUserSchema,

    ClientConversationSchema,
    ClientConversationMemberSchema
};

export type SchemaRegistry = typeof SCHEMA_REGISTRY;
export type SchemaId = keyof SchemaRegistry;
